import { DataFilters } from '../../../components/DataFilters'
import { categoryEntries } from '../../../config/categoryConfig'
import type { AlertStatusFilter } from '../types'

type LowStockFiltersProps = { searchTerm: string; onSearchChange: (value: string) => void; dateRange: { fromDate: string; toDate: string }; onDateRangeChange: (range: { fromDate: string; toDate: string }) => void; statusFilter: AlertStatusFilter; onStatusFilterChange: (value: AlertStatusFilter) => void; projectFilter: string; onProjectFilterChange: (value: string) => void; categoryFilter: string; onCategoryFilterChange: (value: string) => void; projectOptions: string[] }
const selectClassName = 'w-full rounded-2xl border border-[var(--app-border)] bg-white px-4 py-2.5 text-sm text-slate-900 outline-none transition focus:border-slate-400'
const labelClassName = 'min-w-[190px] flex-[0_1_230px] space-y-2'

export function LowStockFilters(props: LowStockFiltersProps) {
  return <DataFilters searchValue={props.searchTerm} onSearchChange={props.onSearchChange} showDateFilter dateRange={props.dateRange} onDateRangeChange={props.onDateRangeChange} searchPlaceholder="ابحث باسم الصنف أو السجل أو القسم"><label className={labelClassName}><span className="block text-sm font-medium text-slate-700">نوع التنبيه</span><select value={props.statusFilter} onChange={(event) => props.onStatusFilterChange(event.target.value as AlertStatusFilter)} className={selectClassName}><option value="all">كل التنبيهات</option><option value="low">كمية قليلة</option><option value="out">كمية فارغة</option><option value="expiring">تنتهي خلال شهر</option><option value="expired">منتهي الصلاحية</option></select></label><label className={labelClassName}><span className="block text-sm font-medium text-slate-700">السجل</span><select value={props.projectFilter} onChange={(event) => props.onProjectFilterChange(event.target.value)} className={selectClassName}><option value="all">كل السجلات</option>{props.projectOptions.map((projectName) => <option key={projectName} value={projectName}>{projectName}</option>)}</select></label><label className={labelClassName}><span className="block text-sm font-medium text-slate-700">القسم</span><select value={props.categoryFilter} onChange={(event) => props.onCategoryFilterChange(event.target.value)} className={selectClassName}><option value="all">كل الأقسام</option>{categoryEntries.map(([categoryKey, category]) => <option key={categoryKey} value={categoryKey}>{category.label}</option>)}</select></label></DataFilters>
}
