create extension if not exists pgcrypto;

create table if not exists public.inventory_operations (
  id uuid primary key default gen_random_uuid(),
  import_key text,
  table_name text not null,
  category_name text,
  category_label text,
  item_id bigint not null,
  item_name text,
  item_label text,
  project_name text,
  project text,
  operation_type text not null check (operation_type in ('add', 'issue', 'adjust')),
  quantity numeric not null check (quantity >= 0),
  operation_date date not null,
  previous_balance numeric not null,
  new_balance numeric not null check (new_balance >= 0),
  supplier_name text,
  issued_to text,
  received_by text,
  purchase_order_number text,
  addition_code text,
  issue_code text,
  item_code text,
  notes text,
  created_by text,
  created_at timestamptz not null default now()
);

do $$
declare table_name text;
begin
  foreach table_name in array array['consumables','paints','screws','stock_screws','raw_materials'] loop
    execute format($sql$
      create table if not exists public.%I (
        id bigint generated by default as identity primary key,
        item_key text not null,
        project text,
        item_name text not null,
        transaction_date date,
        issued numeric not null default 0,
        added numeric not null default 0,
        total_added numeric not null default 0,
        total_issued numeric not null default 0,
        stock_balance numeric not null default 0 check (stock_balance >= 0),
        min_quantity numeric not null default 0,
        notes text,
        created_at timestamptz not null default now(),
        updated_at timestamptz not null default now()
      )
    $sql$, table_name);
  end loop;
end $$;

alter table public.paints add column if not exists expire_date date;
alter table public.screws add column if not exists din text;
alter table public.screws add column if not exists code_number text;
alter table public.stock_screws add column if not exists din text;
alter table public.stock_screws add column if not exists code_number text;
alter table public.raw_materials add column if not exists weight numeric;
alter table public.raw_materials add column if not exists length numeric;
alter table public.raw_materials add column if not exists width numeric;
alter table public.raw_materials add column if not exists th numeric;
alter table public.raw_materials add column if not exists material_source text;

create table if not exists public.cylinders (
  id bigint generated by default as identity primary key,
  item_key text not null,
  type_name text not null,
  gas_balance numeric not null default 0 check (gas_balance >= 0),
  empty_count numeric not null default 0,
  full_count numeric not null default 0,
  transaction_date date,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cutting_discs (
  id bigint generated by default as identity primary key,
  type_name text not null,
  code text,
  received_by text,
  received_date date,
  scrapped_date date,
  source_sheet text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.long_welding_gloves (
  id bigint generated by default as identity primary key,
  type_name text not null,
  code text,
  quantity numeric not null default 1,
  received_by text,
  received_date date,
  scrapped_date date,
  source_sheet text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.imports (
  id bigint generated by default as identity primary key,
  file_name text not null,
  total_rows integer not null default 0,
  matched_sheets jsonb not null default '[]',
  ignored_sheets jsonb not null default '[]',
  rows_by_table jsonb not null default '{}',
  parsing_errors jsonb not null default '[]',
  status text not null,
  imported_at timestamptz not null default now()
);
